apiVersion: v1
kind: Service
metadata:
  name: nats-svc
  labels:
    app.kubernetes.io/name: nats
spec:
  selector:
    app.kubernetes.io/name: nats
  ports:
    - name: client
      port: 4222
      targetPort: 4222
    - name: cluster
      port: 6222
      targetPort: 6222
    - name: http
      port: 8222
      targetPort: 8222