apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-random-wiki-cron
spec:
  schedule: "0 */8 * * *"   # every 8 hours
  timeZone: "UTC"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 2
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 600
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 7200
      backoffLimit: 2
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: todo-cronjob
              image: PROJECT/todo-cronjob
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  cpu: 25m
                  memory: 64Mi
                limits:
                  cpu: 100m
                  memory: 128Mi
              envFrom:
                - configMapRef:
                    name: todo-config